---
- name: template Jinja2
  hosts: stage
  become: yes
  vars:
    SERVER_NAME: Test
    USER: testadmin
  tasks:
    - name: copy using template
      template:
        src: conf.j2
        dest: /etc/conf.txt
        owner: testadmin
        group: testadmin
        mode: '0644'