---
- name: local exec
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  
  tasks:
    - name: print hello
      debug:
        msg: "Hello World"